sudo: required

services:
  - docker

script:
  - docker build -t frontend:test .
  - docker run --rm -p 9876:9876 -v $TRAVIS_BUILD_DIR:/amika-frontend -v /amika-frontend/node_modules frontend:test ng test --watch=false
  - docker run --rm -p 9876:9876 -v $TRAVIS_BUILD_DIR:/amika-frontend -v /amika-frontend/node_modules frontend:test ng e2e