FROM node:12.0-alpine
ENV CHROME_BIN="/usr/bin/chromium-browser" \
    PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
RUN set -x \
    && apk update \
    && apk upgrade \
    && apk add --no-cache udev ttf-freefont chromium \
    && npm install puppeteer@1.10.0

WORKDIR /amika-frontend-tests
COPY package*.json ./
RUN npm install npm && \
    npm install
ENV PATH /amika-frontend-tests/node_modules/.bin:$PATH
COPY . ./
EXPOSE 4200
