version: '3.5'

services:
  frontend:
    container_name: frontend
    restart: always
    image: frontend:latest
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/amika-frontend
    command: ng serve --host 0 --port 4200
    networks:
      - amika-net

networks: 
  amika-net:
    name: amika-net
    driver: bridge