version: '3'

services:
  frontend-tests:
    container_name: frontend-tests
    restart: always
    image: frontend-tests:latest
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/amika-frontend-tests
      - /amika-frontend-tests/node_modules
    ports:
      - 4201:4200
    command: ng serve --host 0 --port 4201
